# Generated by Django 5.1.6 on 2025-03-25 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Excellent', 'Excellent (16-20)'), ('Good', 'Good (11-15)'), ('Caution', 'Caution (0-10)')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('steps', models.JSONField(help_text='List of action items as strings')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='Unknown', max_length=60)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentalHealthTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('Excellent', 'Excellent (16-20)'), ('Good', 'Good (11-15)'), ('Caution', 'Caution (0-10)')], max_length=20)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompletedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.CharField(max_length=200)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('plan_category', models.CharField(choices=[('Excellent', 'Excellent (16-20)'), ('Good', 'Good (11-15)'), ('Caution', 'Caution (0-10)')], max_length=20)),
                ('completed_date', models.DateField(auto_now_add=True)),
                ('state_context', models.CharField(choices=[('Excellent', 'Excellent (16-20)'), ('Good', 'Good (11-15)'), ('Caution', 'Caution (0-10)')], default='Good', max_length=20)),
                ('test_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_actions', to='users.mentalhealthtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'action_text', 'completed_date')},
            },
        ),
        migrations.AddField(
            model_name='mentalhealthtest',
            name='related_actions',
            field=models.ManyToManyField(blank=True, to='users.usercompletedaction'),
        ),
    ]
