# Generated by Django 5.1.6 on 2025-03-25 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompletedaction',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='usercompletedaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mentalhealthtest',
            name='related_actions',
        ),
        migrations.AddField(
            model_name='usercompletedaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('carried', 'Carried Forward')], default='completed', max_length=10),
        ),
        migrations.AlterField(
            model_name='usercompletedaction',
            name='state_context',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Caution', 'Caution')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='usercompletedaction',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='usercompletedaction',
            name='plan_category',
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('state_context', models.CharField(choices=[('Excellent', 'Excellent (16-20)'), ('Good', 'Good (11-15)'), ('Caution', 'Caution (0-10)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('carried', 'Carried Forward'), ('archived', 'Archived')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='users.mentalhealthtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_usera_user_id_8d7a60_idx'), models.Index(fields=['created_at'], name='users_usera_created_73d423_idx')],
            },
        ),
    ]
