# Generated by Django 5.1.6 on 2025-03-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_action_status_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompletedaction',
            options={'ordering': ['-completed_at']},
        ),
    ]
