# Generated by Django 5.1.6 on 2025-03-25 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usercompletedaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompletedaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
