# Generated by Django 5.1.6 on 2025-03-25 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usercompletedaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompletedaction',
            name='completed_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
