# Generated by Django 5.1.6 on 2025-03-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usercompletedaction_completed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mentalhealthtest',
            name='related_actions',
            field=models.ManyToManyField(related_name='tests', to='users.action'),
        ),
    ]
