# Generated by Django 5.1.6 on 2025-03-25 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_action_mentalhealthtest_related_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompletedaction',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='usercompletedaction',
            name='test_context',
        ),
        migrations.AddField(
            model_name='usercompletedaction',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercompletedaction',
            name='related_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.mentalhealthtest'),
        ),
        migrations.AlterField(
            model_name='usercompletedaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercompletedaction',
            name='state_context',
            field=models.CharField(choices=[('Excellent', 'Excellent (16-20)'), ('Good', 'Good (11-15)'), ('Caution', 'Caution (0-10)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usercompletedaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('carried', 'Carried Forward'), ('archived', 'Archived')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='usercompletedaction',
            index=models.Index(fields=['user', 'status'], name='users_userc_user_id_29d8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompletedaction',
            index=models.Index(fields=['completed_at'], name='users_userc_complet_afd9ba_idx'),
        ),
    ]
