# Generated by Django 5.1.6 on 2025-03-25 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_usercompletedaction_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_health_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercompletedaction',
            name='related_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_actions', to='users.mentalhealthtest'),
        ),
    ]
