# Generated by Django 5.1.6 on 2025-03-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_fix_related_names'),
    ]

    operations = [
    ]
