# Generated by Django 5.1.7 on 2025-03-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_fix_action_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='action_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.actionplan'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='steps',
            field=models.JSONField(),
        ),
    ]
