# Generated by Django 5.1.7 on 2025-04-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_moodentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='anxiety_level',
            field=models.CharField(choices=[('none', 'Not at all'), ('mild', 'A little'), ('moderate', 'Quite a bit'), ('severe', 'Very much')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='depression_level',
            field=models.CharField(choices=[('none', 'Not at all'), ('mild', 'A little'), ('moderate', 'Quite a bit'), ('severe', 'Very much')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='energy_level',
            field=models.CharField(choices=[('none', 'Not at all'), ('mild', 'A little'), ('moderate', 'Quite a bit'), ('severe', 'Very much')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='stress_level',
            field=models.CharField(choices=[('none', 'Not at all'), ('mild', 'A little'), ('moderate', 'Quite a bit'), ('severe', 'Very much')], max_length=20),
        ),
    ]
