# Generated by Django 5.1.6 on 2025-09-13 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_moodentry_anxiety_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthtest',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentalhealthtest',
            name='test_type',
            field=models.CharField(choices=[('PHQ-9', 'PHQ-9 (Depression)'), ('GAD-7', 'GAD-7 (Anxiety)'), ('PSS', 'PSS (Perceived Stress)')], default='PHQ-9', max_length=10),
        ),
    ]
