# Generated by Django 5.1.6 on 2025-09-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_test_type_and_date_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalhealthtest',
            name='taken_at',
        ),
    ]
