# Generated by Django 5.1.6 on 2025-09-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_resource_chatsession_chatmessage_resourceclick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthtest',
            name='phq9_item9_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
