# Generated by Django 5.1.6 on 2025-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditationsession',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
