# Generated by Django 5.1.7 on 2025-03-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0003_meditationscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeditationScore',
        ),
    ]
