# Generated by Django 5.1.7 on 2025-03-28 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0004_delete_meditationscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meditationsession',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='meditationsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='meditationsession',
            unique_together={('user', 'date')},
        ),
    ]
